name = "gridflow-control-api"
main = "src/worker.py"
compatibility_date = "2026-08-11"
compatibility_flags = ["python_workers", "disable_python_external_sdk"]

[[durable_objects.bindings]]
name = "EVENT_STATE"
class_name = "EventState"

[[durable_objects.bindings]]
name = "REFERENCE_STATE"
class_name = "ReferenceState"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["EventState"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["ReferenceState"]
